package com.cloudcart.product.model;

import com.cloudcart.product.enums.Category;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.math.BigDecimal;
import java.util.UUID;

@Entity
@Data
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;                                // <- Generated by our system
    @NotBlank
    @Column(nullable = false)
    private String name;
    @Enumerated(EnumType.STRING)
    @NotNull
    @Column(nullable = false)
    private Category category;
    @Column(nullable = false, precision = 19, scale = 2)
    @NotNull
    private BigDecimal price;
    @NotNull
    private String description;
    @NotBlank
    @Column(nullable = false, unique = true)
    private String sku;                             // <- supplied by client, UNIQUE
}
